tag1 = int(input("Masukkan besaran : "))
tag2 = int(input("Masukkan besaran : "))
tag3 = int(input("Masukkan besaran : "))
tag4 = int(input("Masukkan besaran : "))
tag5 = int(input("Masukkan besaran : "))
tag6 = int(input("Masukkan besaran : "))
tag7 = int(input("Masukkan besaran : "))
tag8 = int(input("Masukkan besaran : "))
tag9 = int(input("Masukkan besaran : "))
tag10 = int(input("Masukkan besaran : "))
tag11 = int(input("Masukkan besaran : "))
tagihan = (tag1 , tag2, tag3, tag4, tag5, tag6, tag7, tag8, tag9, tag10, tag11)
total = tag1 +tag2+tag3+tag4+tag5+tag6+tag7+tag8+tag9+tag10+tag11
print("Jumlah Tagihan Adalah : ", total)
